#!/usr/bin/env ruby

# Daemons sets pwd to /, so we have to explicitly set RAILS_ROOT
RAILS_ROOT = File.expand_path(File.join(File.dirname(__FILE__), '..'))

require File.join(File.dirname(__FILE__), *%w(.. vendor gems collectiveidea-delayed_job-1.8.0 lib delayed command))
Delayed::Command.new(ARGV).daemonize
